### ISSUE TITLE
./dataset/1_train.json'

### ISSUE THREAD

**Issue by null1024-ws** [agwaBom/AsmDepictor#2]
When I tried to run "python ./load_model_extract.py", there was an error "FileNotFoundError: [Errno 2] No such file or directory: './dataset/1_train.json". Where can I find the dataset in this format?

**Comment by agwaBom** [comment]
Hello, you can use "learn_model_from_scratch.py" to convert the text data into a JSON format.
The code below is the part where the text file is converted into JSON.
The input text data is found at [LINK](https://zenodo.org/records/7978756).
I plan to clean the code for easier readability and usability.
Thank you :)
```
    train_src_dir = "./dataset/train_source.txt"
    valid_src_dir = "./dataset/test_source.txt"
    test_src_dir = "./dataset/test_source.txt"

    train_tgt_dir = "./dataset/train_target.txt"
    valid_tgt_dir = "./dataset/test_target.txt"
    test_tgt_dir = "./dataset/test_target.txt"

    train_set = preprocessing(train_src_dir, train_tgt_dir, max_token_seq_len)
    valid_set = preprocessing(valid_src_dir, valid_tgt_dir, max_token_seq_len)
    test_set = preprocessing(test_src_dir, test_tgt_dir, max_token_seq_len)

    train_set.to_json('dataset/train.json', orient='records', lines=True)
    valid_set.to_json('dataset/valid.json', orient='records', lines=True)
    test_set.to_json('dataset/test.json', orient='records', lines=True)
```

**Comment by null1024-ws** [comment]
Thanks for your help. Have a nice day~
